var events = [
    {
      startsAt: "Jul 22, 2021 00:00:00",
      endsAt: "Jul 23, 2021 23:59:59",
      endsInText: "Ends in ",
      headline: "Day At Sea",
      copy: "Limited time offers for you!",
      bg: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/day-at-sea/bg-DayAtSea.jpg"],
      decorL: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/day-at-sea/shell-Left.png"],
      decorR: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/day-at-sea/shell-Right.png"],
      items: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/day-at-sea/items2.png"]
    },
    {
      startsAt: "Jul 29, 2021 00:00:00",
      endsAt: "Jul 30, 2021 23:59:59",
      endsInText: "Ends in ",
      headline: "Hotdog Day",
      copy: "Limited time offers for you!",
      bg: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/hotdog-day/bg.jpg"],
      decorL: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/hotdog-day/decor_L.png"],
      decorR: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/hotdog-day/decor_R.png"],
      items: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/hotdog-day/items.png"],
      character: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/hotdog-day/character-hotdog.png"],
    },
    {
      startsAt: "Aug 05, 2021 00:00:00",
      endsAt: "Aug 06, 2021 23:59:59",
      endsInText: "Ends in ",
      headline: "Lasagna Day",
      copy: "Limited time offers for you!",
      bg: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/lasagna-day/bg.jpg"],    
      decorL: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/lasagna-day/decor_L.png"],
      decorR: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/lasagna-day/decor_R.png"],
      items: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/lasagna-day/items.png"],
      character: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/lasagna-day/chef_1.png"],
    },
    {
      startsAt: "Aug 12, 2021 00:00:00",
      endsAt: "Aug 13, 2021 23:59:59",
      endsInText: "Ends in ",
      headline: "Cat Day",
      copy: "Limited time offers for you!",
      bg: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/cat-day/bg.jpg"],    
      decorL: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/cat-day/decor-L.png"],
      decorR: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/cat-day/decor-R.png"],
      items: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/cat-day/items.png"],
      character: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/cat-day/cat.png"],
    },
    {
      startsAt: "Aug 15, 2021 00:00:00",
      endsAt: "Aug 16, 2021 23:59:59",
      endsInText: "Ends in ",
      headline: "Creightons birthday",
      copy: "Limited time offers for you!",
      bg: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/creightons-birthday/bg.jpg"],    
      decorL: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/creightons-birthday/decor-L.png"],
      decorR: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/creightons-birthday/decor-R.png"],
      items: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/creightons-birthday/items.png"],
      discount: ["https://assets.remerge.io/dpa/MytonaCD-offers/July-August/creightons-birthday/discount.png"],
    }
  ];
